### ISSUE TITLE
HLK-FR1002

### ISSUE THREAD

**Issue by jonny190** [Chreece/FaceRec_ESPHome#3]
Is there anyway to support this module? 

https://www.aliexpress.com/item/1005005066346653.html

As its more compact and could easily fit inside a CCTV Dome by the door? 

I cant find any English documentation for it [Only this](http://h.hlktech.com/Mobile/Download/fdetail/215.html) or I'd attempt it myself, but Ive tested it in windows using the Demo software and the hardware works.

Happy to supply the hardware if it would help?

**Comment by akeilox** [comment]
that would be really cool indeed!

**Comment by jonny190** [comment]
I've reached out and managed to get an English copy of the docs:
[FR1002 Face recognition module user manual V1.0.3.pdf](https://github.com/Chreece/FaceRec_ESPHome/files/13817748/FR1002.Face.recognition.module.user.manual.V1.0.3.pdf)

**Comment by Chreece** [comment]
Sorry, it's something I'm not interested on...

**Comment by cenepio** [comment]
"How can I retrieve the user ID when facial recognition is successful in the fr1002 module of the library created by jonny190? I'm a beginner and not sure about this, so I wanted to inquire."

**Comment by jonny190** [comment]
> "How can I retrieve the user ID when facial recognition is successful in the fr1002 module of the library created by jonny190? I'm a beginner and not sure about this, so I wanted to inquire."

Thats why i was asking help from @Chreece as i'm a but stuck as well. Using my fork of the code it will return a matched face but its in the Hex string rather then the ID (this can be seen in the esphome web interface
![image](https://github.com/Chreece/FaceRec_ESPHome/assets/8059327/b67a4788-9f56-4c64-8b2e-4bd6e3733392)

I just need a hand decoding it back in to a text string..... that screenshot contains :

`17:49:25 | [D] | [button:010] | 'Start Identify: 3DFace' Pressed.

17:49:25 | [D] | [uart_debug:114] | >>> EF,AA,12,00,02,00,02,12

17:49:27 | [D] | [uart_debug:114] | <<< EF,AA,00,00,26,12,00,00,01,4A,6F,6E,6E,79,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,01,00,68`

This is the encoded string for Jonny (The user its detected) I just dont know how to get that back to a string output in esphome

**Comment by akeilox** [comment]
01,4A,6F,6E,6E,79
is the hex for Jonny I believe
and the ID should be encoded as integer at the front of that

**Comment by jonny190** [comment]
Yeah i got some progress on the [Home assistant forums](https://community.home-assistant.io/t/hlk-fr1002-facial-recognition/665065/3) but i'm at a loss on how to code it from the hex to a human readable output

**Comment by cenepio** [comment]
void name() {
  if (Serial.available() > 0) {
    // Read hexadecimal values until a newline character is encountered
    String hexString = Serial.readStringUntil('\n');
    
    // Trim leading and trailing whitespaces from the string
    hexString.trim();

    if (hexString.length() >= 32) {
      // Convert hexadecimal to decimal and then to ASCII, printing the result
      for (int i = 8; i < 32; i += 2) {
        // Extract two characters at a time to form a hexadecimal byte
        String hexByte = hexString.substring(i, i + 2);
        
        // Convert the hexadecimal byte to decimal
        int decimalValue = strtol(hexByte.c_str(), NULL, 16);
        
        // Convert the decimal value to ASCII and print
        char asciiChar = char(decimalValue);
        Serial.print(asciiChar);
      }
      
      // Print a newline character at the end of the line
      Serial.println();
    }
  }
}

Would it work if I write the code like this?

**Comment by cenepio** [comment]
void processSerialData(byte receivedData[]) {
  int id = (receivedData[6] << 8) | receivedData[7];
  Serial.print("ID: ");
  Serial.println(id);

  Serial.print("ASCII: ");
  for (int i = 8; i < 40; i++) {
    char asciiChar = receivedData[i];
    Serial.print(asciiChar);
  }

  Serial.println();

**Comment by cenepio** [comment]
void processSerialData(byte receivedData[]) {
  int id = (receivedData[6] << 8) | receivedData[7];
  Serial.print("ID: ");
  Serial.println(id);

**Comment by akeilox** [comment]
EF,AA,00,00,26,12,00,**00,01,STRING-NAME,01,00**...

Head EF AA
Type 00
Data Length 00 26
Response Command 12
Error code 00

The string-name is in between two 01
max 32 characters

**Comment by Chreece** [comment]
Sorry, I'm very busy with other projects
